/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
/*
 * Jihad Browser — real BrowserServer daemon with the Goanna backend.
 * Subclasses the unchanged autogenerated BrowserServerBase YAP dispatch. Each
 * connected client/page gets its own BrowserPageGoanna and a ProxySink that
 * forwards that page's msg* to that client's YapProxy (multi-page safe; Codex
 * P0). Builds against libYap (ref-BrowserServer/Yap) — no Qt.
 */
#ifndef JIHAD_BROWSERSERVER_H
#define JIHAD_BROWSERSERVER_H

#include <BrowserServerBase.h>
#include "../goanna/BrowserPageGoanna.h"
#include <map>
#include <vector>

namespace jihad { class EngineHost; }
class JihadBrowserServer;

// Per-page message sink: routes a page's msg* to that page's client proxy.
class ProxySink : public jihad::IPageMessageSink {
public:
  ProxySink(JihadBrowserServer* srv, YapProxy* proxy) : mSrv(srv), mProxy(proxy) {}
  void msgPainted(int32_t key) override;
  void msgLoadStarted() override;
  void msgLoadProgress(int32_t p) override;
  void msgLoadStopped() override;
  void msgLocationChanged(const char* uri, bool b, bool f) override;
  void msgTitleChanged(const char* t) override;
  void msgTitleAndUrlChanged(const char* title, const char* uri, bool b, bool f) override;
  void msgEditorFocused(bool focused, int fieldType, int fieldActions) override;
  void msgContentsSizeChanged(int32_t w, int32_t h) override;
  void msgScrolledTo(int32_t x, int32_t y) override;
  void msgMetaViewportSet(double is, double mn, double mx, int32_t w, int32_t h, bool us) override;
  void msgFailedLoad(const char* domain, int32_t code, const char* url, const char* description) override;
  void msgUpdateGlobalHistory(const char* url, bool reload) override;
  void msgUrlRedirected(const char* url, const char* userData) override;
  void msgSSLConfirm(const char* host, int32_t code, const char* certFile) override;
  void msgLinkClicked(const char* url) override;
private:
  JihadBrowserServer* mSrv;
  YapProxy*           mProxy;
};

class JihadBrowserServer : public BrowserServerBase
{
public:
  JihadBrowserServer(const char* name, jihad::EngineHost& host);
  virtual ~JihadBrowserServer();

  virtual void clientConnected(YapProxy* proxy);
  virtual void clientDisconnected(YapProxy* proxy);

  void tick();   // engine + paint pump for all pages (GLib timeout)

  void syncCmdRenderToFile(YapProxy* proxy, const char* filename, int32_t viewX, int32_t viewY, int32_t viewW, int32_t viewH, int32_t& result) override;
  void asyncCmdConnect(YapProxy* proxy, int32_t pageWidth, int32_t pageHeight, int32_t sharedBufferKey1, int32_t sharedBufferKey2, int32_t sharedBufferSize, int32_t identifier) override;
  void asyncCmdSetWindowSize(YapProxy* proxy, int32_t width, int32_t height) override;
  void asyncCmdSetUserAgent(YapProxy* proxy, const char* userAgent) override;
  void asyncCmdOpenUrl(YapProxy* proxy, const char* url) override;
  void asyncCmdSetHtml(YapProxy* proxy, const char* url, const char* body) override;
  void asyncCmdClickAt(YapProxy* proxy, int32_t contentX, int32_t contentY, int32_t numClicks, int32_t counter) override;
  void asyncCmdKeyDown(YapProxy* proxy, int32_t key, int32_t modifiers, int32_t chr) override;
  void asyncCmdKeyUp(YapProxy* proxy, int32_t key, int32_t modifiers, int32_t chr) override;
  void asyncCmdForward(YapProxy* proxy) override;
  void asyncCmdBack(YapProxy* proxy) override;
  void asyncCmdReload(YapProxy* proxy) override;
  void asyncCmdStop(YapProxy* proxy) override;
  void asyncCmdPageFocused(YapProxy* proxy, bool focused) override;
  void asyncCmdExit(YapProxy* proxy) override;
  void asyncCmdCancelDownload(YapProxy* proxy, const char* url) override;
  void asyncCmdInterrogateClicks(YapProxy* proxy, bool enable) override;
  void asyncCmdZoomSmartCalculateRequest(YapProxy* proxy, int32_t pointX, int32_t pointY) override;
  void asyncCmdDragStart(YapProxy* proxy, int32_t contentX, int32_t contentY) override;
  void asyncCmdDragProcess(YapProxy* proxy, int32_t deltaX, int32_t deltaY) override;
  void asyncCmdDragEnd(YapProxy* proxy, int32_t contentX, int32_t contentY) override;
  void asyncCmdSetMinFontSize(YapProxy* proxy, int32_t minFontSizePt) override;
  void asyncCmdFindString(YapProxy* proxy, const char* str, bool fwd) override;
  void asyncCmdClearSelection(YapProxy* proxy) override;
  void asyncCmdClearCache(YapProxy* proxy) override;
  void asyncCmdClearCookies(YapProxy* proxy) override;
  void asyncCmdPopupMenuSelect(YapProxy* proxy, const char* identifier, int32_t selectedIdx) override;
  void asyncCmdSetEnableJavaScript(YapProxy* proxy, bool enable) override;
  void asyncCmdSetBlockPopups(YapProxy* proxy, bool enable) override;
  void asyncCmdSetAcceptCookies(YapProxy* proxy, bool enable) override;
  void asyncCmdMouseEvent(YapProxy* proxy, int32_t type, int32_t contentX, int32_t contentY, int32_t detail) override;
  void asyncCmdGestureEvent(YapProxy* proxy, int32_t type, int32_t contentX, int32_t contentY, double scale, double rotate, int32_t centerX, int32_t centerY) override;
  void asyncCmdDisconnect(YapProxy* proxy) override;
  void asyncCmdInspectUrlAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) override;
  void asyncCmdGetHistoryState(YapProxy* proxy, int32_t queryNum) override;
  void asyncCmdClearHistory(YapProxy* proxy) override;
  void asyncCmdSetAppIdentifier(YapProxy* proxy, const char* identifier) override;
  void asyncCmdAddUrlRedirect(YapProxy* proxy, const char* urlRe, int32_t type, bool redirect, const char* userData) override;
  void asyncCmdSetShowClickedLink(YapProxy* proxy, bool enable) override;
  void asyncCmdGetInteractiveNodeRects(YapProxy* proxy, int32_t pointX, int32_t pointY) override;
  void asyncCmdIsEditing(YapProxy* proxy, int32_t queryNum) override;
  void asyncCmdInsertStringAtCursor(YapProxy* proxy, const char* text) override;
  void asyncCmdEnableSelection(YapProxy* proxy, int32_t pointX, int32_t pointY) override;
  void asyncCmdDisableSelection(YapProxy* proxy) override;
  void asyncCmdSaveImageAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY, const char* dstDir) override;
  void asyncCmdGetImageInfoAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) override;
  void asyncCmdIsInteractiveAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) override;
  void asyncCmdGetElementInfoAtPoint(YapProxy* proxy, int32_t queryNum, int32_t pointX, int32_t pointY) override;
  void asyncCmdSelectAll(YapProxy* proxy) override;
  void asyncCmdCopy(YapProxy* proxy, int32_t queryNum) override;
  void asyncCmdPaste(YapProxy* proxy) override;
  void asyncCmdCut(YapProxy* proxy) override;
  void asyncCmdSetMouseMode(YapProxy* proxy, int32_t mode) override;
  void asyncCmdDisableEnhancedViewport(YapProxy* proxy, bool disable) override;
  void asyncCmdIgnoreMetaTags(YapProxy* proxy, bool ignore) override;
  void asyncCmdSetScrollPosition(YapProxy* proxy, int32_t cx, int32_t cy, int32_t cw, int32_t ch) override;
  void asyncCmdPluginSpotlightStart(YapProxy* proxy, int32_t cx, int32_t cy, int32_t cw, int32_t ch) override;
  void asyncCmdPluginSpotlightEnd(YapProxy* proxy) override;
  void asyncCmdHideSpellingWidget(YapProxy* proxy) override;
  void asyncCmdSetNetworkInterface(YapProxy* proxy, const char* interfaceName) override;
  void asyncCmdHitTest(YapProxy* proxy, int32_t queryNum, int32_t cx, int32_t cy) override;
  void asyncCmdSetVirtualWindowSize(YapProxy* proxy, int32_t width, int32_t height) override;
  void asyncCmdPrintFrame(YapProxy* proxy, const char* frameName, int32_t lpsJobId, int32_t width, int32_t height, int32_t dpi, bool landscape, bool reverseOrder) override;
  void asyncCmdTouchEvent(YapProxy* proxy, int32_t type, int32_t touchCount, int32_t modifiers, const char* touchesJson) override;
  void asyncCmdHoldAt(YapProxy* proxy, int32_t contentX, int32_t contentY) override;
  void asyncCmdGetTextCaretBounds(YapProxy* proxy, int32_t queryNum) override;
  void asyncCmdFreeze(YapProxy* proxy) override;
  void asyncCmdThaw(YapProxy* proxy, int32_t sharedBufferKey1, int32_t sharedBufferKey2, int32_t sharedBufferSize) override;
  void asyncCmdReturnBuffer(YapProxy* proxy, int32_t sharedBufferKey) override;
  void asyncCmdSetZoomAndScroll(YapProxy* proxy, double zoom, int32_t cx, int32_t cy) override;
  void asyncCmdScrollLayer(YapProxy* proxy, int32_t id, int32_t deltaX, int32_t deltaY) override;
  void asyncCmdSetDNSServers(YapProxy* proxy, const char* servers) override;

private:
  struct Page { jihad::BrowserPageGoanna* page; ProxySink* sink; };
  jihad::BrowserPageGoanna* pageFor(YapProxy* proxy);
  void reap(YapProxy* proxy);   // destroy a client's page (deferred during tick)
  // Dev-only input injection: consume + apply command lines from the inject
  // file against the last-connected page. Inert unless the file exists (the
  // path only exists on-device). See docs in JihadBrowserServer.cpp.
  void processInjectFile();

  jihad::EngineHost&               mHost;
  std::map<YapProxy*, Page>        mPages;
  std::vector<Page>                mReap;    // deleted after the tick loop
  bool                             mInTick;
  YapProxy*                        mLastProxy = nullptr;  // last-connected (active card)
  int                              mInjectThrottle = 0;   // check the file ~5x/s, not per-tick
};

#endif // JIHAD_BROWSERSERVER_H
