#!/bin/sh
# Copyright 2026 NotAlexNoyle. Apache-2.0.
#
# Generate the per-variant install artifacts for the three INDEPENDENT Jihad Browser packages
# (cavekit-device-build.md R7 + R8; identity table: context/plans/plan-variant-identity.md):
#
#     packaging/<variant>/postinst      packaging/<variant>/prerm      packaging/event.d/<job>
#
# WHY A GENERATOR AND NOT THREE HAND-WRITTEN COPIES
#   The three packages share no file on the device — that is the whole point of R7 — but their
#   install LOGIC is identical; only the identity row differs. Hand-maintaining three copies is
#   how the pre-2026-07-31 packaging grew its cross-variant bugs (a `rm -f /tmp/yapserver.
#   jihad-browser*` glob in one script silently owning the other two variants' sockets). One
#   template + one table makes a cross-variant reference impossible to write by accident: every
#   variant-specific string in the output came from this file's TABLE.
#   The generated files are CHECKED IN — they are what actually ships, so they must be readable
#   and diffable — and `--check` proves they still match the template.
#
# Usage:
#   sh packaging/gen-variant-scripts.sh            regenerate the 9 artifacts in place
#   sh packaging/gen-variant-scripts.sh --check    fail (exit 1) if any checked-in file has drifted
set -eu

HERE=$(cd "$(dirname "$0")" && pwd)

MODE=write
if [ "${1:-}" = "--check" ]; then MODE=check; fi

# ---------------------------------------------------------------------------------------------
# THE IDENTITY TABLE — the only place a variant-specific string may be written.
# Mirrors context/plans/plan-variant-identity.md and build/webos-oe/recipes-jihad/
# jihad-variants.inc (the OE side). Fields, colon-separated:
#
#   1 variant token   2 app id   3 NPAPI shim .so   4 upstart job   5 YAP service name   6 label
#
# Derived, never written by hand: the socket is /tmp/yapserver.<YAP name>, the adapter impl is
# /usr/lib/jihad/<variant>/BrowserAdapterImpl.so, the state dir is /var/palm/jihad/<variant>/.
# ---------------------------------------------------------------------------------------------
TABLE="
enyo:net.riverstonerelay.jihad-browser:BrowserAdapterJihad.so:jihad:jihad-browser:Enyo 1.0
mochi:net.riverstonerelay.jihad-browser.mochi:BrowserAdapterJihadMochi.so:jihad-mochi:jihad-browser-mochi:Enyo 2 + Mochi
mojo:net.riverstonerelay.jihad-browser.mojo:BrowserAdapterJihadMojo.so:jihad-mojo:jihad-browser-mojo:Mojo
"

# ---------------------------------------------------------------------------------------------
# TEMPLATES. Written with quoted heredocs so NOTHING expands here: every `$` below belongs to
# the generated script. The generator only substitutes the @@…@@ markers from the table.
# ---------------------------------------------------------------------------------------------

emit_postinst() {
	cat <<'TEMPLATE_POSTINST'
#!/bin/sh
# GENERATED by packaging/gen-variant-scripts.sh — DO NOT EDIT THIS FILE.
#   regenerate: sh packaging/gen-variant-scripts.sh          check: … --check
#
# Jihad Browser — @@LABEL@@ variant (@@APPID@@) — post-install.
# Runs as ROOT under Preware / WebOS Quick Install (palm-install does not run control scripts).
#
# The run-in-place-from-cryptofs install model below — leaving the engine in the app's own
# deviceroot instead of copying it to /media/internal, and doing every rootfs write in a single
# remount-rw window — is adapted from the Atlas browser's
# atlas-browser-app/packaging/ipk-postinst.sh (Apache-2.0, Herman van Hazendonk / Herrie82).
#
# ── INSTALL FOOTPRINT (cavekit-device-build.md R8; enumerated in packaging/README.md) ─────────
# Everything this script creates outside the app's own directory, and nothing else:
#   /usr/lib/BrowserPlugins/@@SHIM@@
#         the NPAPI shim. Unavoidable rootfs write: webOS WebKit builds its plugin/MIME database
#         by scanning /usr/lib/BrowserPlugins at BOOT, and that is the only path it loads a
#         plugin from (Atlas hit the same wall and found no way around it). Bounded + reversed
#         instead of pretended away.
#   /usr/lib/jihad/@@V@@/BrowserAdapterImpl.so
#         the adapter implementation. It lives on the ROOTFS, not in the app bundle, because the
#         shim dlopens it into privileged LunaSysMgr and fails closed unless the file is
#         root-owned and not group/world-writable (review F-161/F-180) — and cryptofs reports
#         EVERY file as 777, so an app-bundle impl could never pass that check.
#   /etc/event.d/@@JOB@@
#         this variant's own upstart job. The stock `browserserver` job is never touched.
#   /var/palm/jihad/@@V@@/
#         root-owned 0755 runtime state (daemon log). Root-owned and NOT world-writable: it is
#         read by root-privileged code, and /media/internal (world-writable vfat) is exactly the
#         location the shim's trust check exists to distrust.
#
# NOT written, deliberately:
#   * NOTHING under /media/internal. That vfat volume is the user's USB mass-storage partition
#     and must stay free of app internals (user decision 2026-07-31; Atlas's model). The daemon,
#     libxul, the bundled glibc-2.23 and the GRE resources RUN IN PLACE from $APP/deviceroot/hl
#     on cryptofs — measured live 2026-07-31: /media/cryptofs is fuse.cryptofs (rw,nosuid,nodev)
#     and is NOT noexec, and a binary copied into an app dir was proven to execute there.
#   * No stock file is modified, replaced, moved, or backed-up-and-swapped. In particular
#     /usr/lib/BrowserPlugins/BrowserAdapter.so, …/BrowserAdapterMojo.so and
#     /etc/event.d/browserserver keep their stock bytes.
#   * No file owned by another Jihad variant. Every path above carries this variant's token, so
#     installing this package cannot overwrite, downgrade, or invalidate anything the Enyo /
#     Mochi / Mojo siblings own (R7).
#
# Reversed EXACTLY by this variant's prerm.
set -e                              # review #6: a failed deploy must NOT report success

V=@@V@@
APP=/media/cryptofs/apps/usr/palm/applications/@@APPID@@
DR=$APP/deviceroot
HL=$DR/hl
SHIM=/usr/lib/BrowserPlugins/@@SHIM@@
IMPLDIR=/usr/lib/jihad/@@V@@
IMPL=$IMPLDIR/BrowserAdapterImpl.so
JOB=/etc/event.d/@@JOB@@
STATE=/var/palm/jihad/@@V@@
log() { echo "jihad-postinst($V): $*"; }

# ── 0. preflight ─────────────────────────────────────────────────────────────────────────────
# Nothing on the system is touched until the whole payload is present, so a truncated download
# or a mis-assembled .ipk fails BEFORE it can half-install (review #6).
[ -f "$HL/jihad-browserserver" ] && [ -f "$HL/ld-2.23.so" ] \
  && [ -f "$DR/BrowserPlugins/@@SHIM@@" ] && [ -f "$DR/event.d/@@JOB@@" ] \
  && [ -f "$APP/BrowserAdapterImpl.so" ] || {
	echo "jihad-postinst($V): bundle payload missing under $APP — aborting" >&2; exit 1; }

# ── 1. engine + daemon: RUN IN PLACE, copy nothing ───────────────────────────────────────────
# The whole runtime already sits in the app's own deviceroot on cryptofs and stays there. All
# this step does is make the two things the upstart job execs executable. Non-fatal: cryptofs
# reports every file 777 regardless, and step 3 verifies the result for real.
log "preparing the Goanna daemon (in place, on cryptofs — nothing is copied)..."
chmod 755 "$HL/jihad-browserserver" "$HL/ld-2.23.so" 2>/dev/null || true

# ── 2. the rootfs writes: ONE rw window ──────────────────────────────────────────────────────
# `/` is treated as read-only; the window is opened here and closed by the trap on EVERY exit
# path INCLUDING failure (R8), so a crash mid-install can never leave the rootfs writable.
# /var/palm is created in the same window because it may sit on the read-only rootfs.
log "installing shim + impl + upstart job + state dir (rootfs rw)..."
trap 'mount -o remount,ro / 2>/dev/null || true' EXIT
mount -o remount,rw /
mkdir -p /usr/lib/BrowserPlugins "$IMPLDIR" "$STATE"
# 0755 root-owned, NOT world-writable — see the footprint note above.
chown 0:0 /var/palm/jihad "$STATE" 2>/dev/null || true
chmod 0755 /var/palm/jihad "$STATE"
cp -a "$DR/BrowserPlugins/@@SHIM@@" "$SHIM"
chmod 0755 "$SHIM"
cp -a "$APP/BrowserAdapterImpl.so" "$IMPL"
# The shim REJECTS an impl that is not root-owned or is group/world-writable, and `cp -a`
# preserves the source's cryptofs-reported 777 — so set both explicitly, or the adapter will
# refuse to load its own implementation.
chown 0:0 "$IMPL" 2>/dev/null || true
chmod 0644 "$IMPL"
cp -a "$DR/event.d/@@JOB@@" "$JOB"
chmod 0755 "$JOB"
sync
mount -o remount,ro / 2>/dev/null || true
trap - EXIT

# ── 3. verify the deploy actually landed ─────────────────────────────────────────────────────
# BusyBox `cp` can fail with EBADF across these mounts, so believe the filesystem, not $?.
[ -f "$SHIM" ] && [ -f "$IMPL" ] && [ -f "$JOB" ] && [ -d "$STATE" ] \
  && [ -x "$HL/jihad-browserserver" ] && [ -x "$HL/ld-2.23.so" ] || {
	echo "jihad-postinst($V): deploy verification failed" >&2; exit 1; }

# ── 4. runtime kicks — optional, never fatal (a reboot picks all of this up anyway) ───────────
# `stop` first: on an UPGRADE the previous daemon is still bound to /tmp/yapserver.@@YAP@@ and
# still holds the replaced files open, so a bare `start` would fail and leave the old build
# running. Only this variant's job name is used — never a glob, never another variant's job.
set +e
log "restarting the @@LABEL@@ daemon + reloading LunaSysMgr..."
stop @@JOB@@ 2>/dev/null
start @@JOB@@ 2>/dev/null
# NOTE: a NEW plugin only enters WebKit's MIME database on a full BOOT (it scans
# /usr/lib/BrowserPlugins once, at startup). `killall LunaSysMgr` refreshes the UI but does NOT
# re-scan — after a first install of this variant, REBOOT before expecting its card to render.
killall LunaSysMgr 2>/dev/null
log "install complete."
exit 0
TEMPLATE_POSTINST
}

emit_prerm() {
	cat <<'TEMPLATE_PRERM'
#!/bin/sh
# GENERATED by packaging/gen-variant-scripts.sh — DO NOT EDIT THIS FILE.
#   regenerate: sh packaging/gen-variant-scripts.sh          check: … --check
#
# Jihad Browser — @@LABEL@@ variant (@@APPID@@) — pre-removal. Runs as ROOT.
#
# Removes EXACTLY what this variant's postinst created, and nothing else:
#   /usr/lib/BrowserPlugins/@@SHIM@@
#   /usr/lib/jihad/@@V@@/BrowserAdapterImpl.so   (+ the now-empty /usr/lib/jihad/@@V@@)
#   /etc/event.d/@@JOB@@
#   /var/palm/jihad/@@V@@/                       (the runtime state dir, log included)
#   /tmp/yapserver.@@YAP@@                       (this variant's socket)
# `/usr/lib/jihad` and `/var/palm/jihad` are only ever `rmdir`'d — that succeeds solely when the
# LAST variant is gone, and can never take a sibling's subdirectory with it.
#
# ── TWO PROPERTIES THIS SCRIPT EXISTS TO GUARANTEE ───────────────────────────────────────────
# NO REFCOUNT. The 2026-07-29 review (#4) added a loop that counted sibling
# net.riverstonerelay.jihad-browser* app dirs and skipped teardown while any survived, because
# all variants shared one runtime. Under R7 nothing is co-owned, so that loop is DELETED: this
# package unconditionally removes its own files, and no sibling can be affected either way.
#
# NO GLOBS ACROSS VARIANTS. `rm -f /tmp/yapserver.jihad-browser*` (the old code) deletes the
# Mochi and Mojo sockets; `killall jihad-browserserver` kills their daemons (all three variants
# ship a binary with that name). Every operation below names one exact path or matches one
# exact process.
#
# The engine, daemon, bundled glibc and GRE resources live in $APP/deviceroot and go away with
# the app directory, which the installer removes. There is nothing to clean under
# /media/internal because this package never wrote anything there. That teardown shape is
# adapted from the Atlas browser's atlas-browser-app/packaging/ipk-prerm.sh (Apache-2.0,
# Herman van Hazendonk / Herrie82).

V=@@V@@
APP=/media/cryptofs/apps/usr/palm/applications/@@APPID@@
HL=$APP/deviceroot/hl
SHIM=/usr/lib/BrowserPlugins/@@SHIM@@
IMPLDIR=/usr/lib/jihad/@@V@@
IMPL=$IMPLDIR/BrowserAdapterImpl.so
JOB=/etc/event.d/@@JOB@@
SOCK=/tmp/yapserver.@@YAP@@
STATE=/var/palm/jihad/@@V@@
log() { echo "jihad-prerm($V): $*"; }

# ── 1. stop THIS variant's daemon ─────────────────────────────────────────────────────────────
log "stopping the @@LABEL@@ daemon..."
stop @@JOB@@ 2>/dev/null || true
# Fallback for a daemon upstart is not supervising (started by hand, or orphaned by a crash).
# It must not be `killall jihad-browserserver` — that is every variant's daemon. Instead match
# on argv: the upstart job execs `ld-2.23.so --library-path $HL ./jihad-browserserver $HL`, so
# only THIS variant's processes carry THIS app's bundle directory as an exact argument.
#
# The comparison is done in the shell, NOT with `grep -x`: this device ships BusyBox 1.17.3,
# whose grep supports only -HhnlLoqvsriwFE — there is no -x. `grep -qxF` therefore does not
# match-and-fail, it prints its usage text and returns non-zero for EVERY process, silently
# disabling this whole fallback. (Measured on-device 2026-07-31, after the real removal run
# dumped BusyBox's grep usage into the ipkg output.) A plain -F substring match would work
# today but is a trap for later: the Enyo app id is a prefix of the Mochi and Mojo ones, so it
# only stays safe because the path continues "/deviceroot" — one rename away from killing a
# sibling's daemon. An exact whole-argument comparison has no such edge.
for p in /proc/[0-9]*; do
	[ -r "$p/cmdline" ] || continue
	match=0
	while IFS= read -r arg; do
		[ "$arg" = "$HL" ] && { match=1; break; }
	done <<EOF
$(tr '\0' '\n' < "$p/cmdline" 2>/dev/null)
EOF
	[ "$match" = 1 ] && kill "$(basename "$p")" 2>/dev/null || true
done
rm -f "$SOCK"                       # exact socket path — never a glob (see header)

# ── 2. the rootfs + state removals: ONE rw window, closed on every exit path ──────────────────
log "removing this variant's rootfs components (rw)..."
trap 'mount -o remount,ro / 2>/dev/null || true' EXIT
mount -o remount,rw / 2>/dev/null || true
rm -f "$SHIM"
rm -f "$IMPL"
rmdir "$IMPLDIR" 2>/dev/null || true
rmdir /usr/lib/jihad 2>/dev/null || true    # succeeds only once the LAST variant is gone
rm -f "$JOB"
rm -rf "$STATE"                             # this variant's state dir only
rmdir /var/palm/jihad 2>/dev/null || true   # ditto
sync
mount -o remount,ro / 2>/dev/null || true
trap - EXIT

killall LunaSysMgr 2>/dev/null || true
log "removal complete."
exit 0
TEMPLATE_PRERM
}

emit_upstart() {
	cat <<'TEMPLATE_UPSTART'
# GENERATED by packaging/gen-variant-scripts.sh — DO NOT EDIT THIS FILE.
#   regenerate: sh packaging/gen-variant-scripts.sh          check: … --check
#
# Jihad BrowserServer (UXP/Goanna daemon) — @@LABEL@@ variant. Installed to /etc/event.d/@@JOB@@.
#
# This is THIS VARIANT'S OWN upstart job. It does not touch the stock `browserserver` job, and
# it does not touch the other Jihad variants' jobs: stock /usr/bin/BrowserServer keeps serving
# /tmp/yapserver.browser for every other app, and each Jihad variant serves exactly one socket
# (/tmp/yapserver.@@YAP@@ here), reached only by the card whose WebView asks for that variant's
# plugin MIME. upstart supervises this (respawn) so the browser survives a daemon crash.
#
# RUNS IN PLACE. The daemon, libxul, the bundled glibc-2.23 loader and the GRE resources are
# executed straight out of the app's own cryptofs deviceroot — nothing was ever copied to
# /media/internal (the user's vfat USB storage). Verified live 2026-07-31: /media/cryptofs is
# fuse.cryptofs (rw,nosuid,nodev), NOT noexec, and a binary in an app dir executes there. Model
# adapted from the Atlas browser (atlas-browser-app/packaging/ipk-postinst.sh, Apache-2.0,
# Herman van Hazendonk / Herrie82), which runs its WPE engine in place the same way.
#
# ── HARD-WON: LD_LIBRARY_PATH IS SET ONLY VIA `env`, ON THE EXEC LINE ────────────────────────
# It must NEVER be exported into this script's shell. The bundled gcc9 glibc-2.23 is not
# compatible with the device's 2.8 userland, so an exported LD_LIBRARY_PATH makes /bin/rm,
# mkdir, touch — every command below — load the wrong libc and segfault before the daemon ever
# execs. Keep it on the `exec env` line and nowhere else.
start on stopped fontconfig_cache
stop on started start_update

description "Jihad BrowserServer (Goanna) — @@LABEL@@"

script
	APP=/media/cryptofs/apps/usr/palm/applications/@@APPID@@
	HL=$APP/deviceroot/hl
	STATE=/var/palm/jihad/@@V@@

	# The state dir is created root-owned 0755 by postinst; recreate it best-effort because a
	# device reset / GC wipes /var. If it is genuinely unavailable (e.g. a read-only rootfs at
	# this point in boot) fall back to /dev/null rather than letting a failed redirect kill the
	# job and spin the respawn limit — the daemon itself is still perfectly able to run.
	mkdir -p "$STATE" 2>/dev/null || true
	LOG=$STATE/daemon.log
	touch "$LOG" 2>/dev/null || LOG=/dev/null
	exec >>"$LOG" 2>&1

	# Only this variant's own socket — an exact path, never `…jihad-browser*`, which would
	# delete the other variants' sockets out from under their running daemons.
	rm -f /tmp/yapserver.@@YAP@@

	cd "$HL" || exit 1
	# NB: do NOT set JIHAD_DUMP in normal operation — it makes every paint write a ~2.2 MB PPM
	# char-by-char (fputc), which added ~400 ms of latency PER KEYSTROKE. Set it only when
	# debugging what the engine renders, and point it INSIDE the state dir, never at
	# /media/internal (env JIHAD_DUMP=$STATE/frame.ppm).
	# JIHAD_BS_NAME is this variant's YAP service name — it is what makes the socket, and
	# therefore the whole daemon<->adapter channel, unique per variant.
	# JIHAD_STATE_DIR tells the daemon where its writable state (profile/cache/debug output)
	# belongs; it must never fall back to the user's storage.
	# ICU_DATA is REQUIRED, not a nicety. libxul loads its Unicode tables from icudt78l.dat at
	# XPCOM startup; the path compiled into the engine is the BUILD machine's, which does not
	# exist here, and ICU has no notion of "next to the library". Without this the daemon aborts
	# on every single start with
	#     ###!!! ABORT: u_init() failed: file .../xpcom/build/XPCOMInit.cpp, line 698
	# and upstart respawns it forever. Diagnosed on-device 2026-07-31: identical invocation, the
	# only difference being ICU_DATA, gets past u_init() and on into fontconfig.
	exec env LD_LIBRARY_PATH="$HL" ICU_DATA="$HL" \
	         JIHAD_BS_NAME=@@YAP@@ JIHAD_OFFSCREEN=1 JIHAD_DISABLE_OMTC=1 \
	         JIHAD_STATE_DIR="$STATE" \
	    ./ld-2.23.so --library-path "$HL" ./jihad-browserserver "$HL"
end script

respawn
respawn limit 10 5
TEMPLATE_UPSTART
}

# ---------------------------------------------------------------------------------------------
# Driver.
# ---------------------------------------------------------------------------------------------
subst() {
	# $1 emitter, then the six table fields.
	"$1" | sed \
		-e "s|@@V@@|$2|g" \
		-e "s|@@APPID@@|$3|g" \
		-e "s|@@SHIM@@|$4|g" \
		-e "s|@@JOB@@|$5|g" \
		-e "s|@@YAP@@|$6|g" \
		-e "s|@@LABEL@@|$7|g"
}

# Write $1 (mode $2) with the content on stdin, or — in --check mode — compare and flag drift.
# Both the `while` loop and the right-hand side of the pipe that feeds this run in SUBSHELLS, so
# a shell variable could not carry a drift verdict back out; the marker file can.
DRIFT_MARKER=$HERE/.gen-variant-scripts.drift
put() {
	dest=$1
	mode=$2
	tmp=$dest.gen.$$
	mkdir -p "$(dirname "$dest")"
	cat > "$tmp"
	if [ "$MODE" = check ]; then
		if cmp -s "$tmp" "$dest"; then
			echo "  ok      ${dest#"$HERE"/}"
		else
			echo "  DRIFTED ${dest#"$HERE"/}" >&2
			: > "$DRIFT_MARKER"
		fi
		rm -f "$tmp"
	else
		chmod "$mode" "$tmp"
		mv "$tmp" "$dest"
		echo "  wrote   ${dest#"$HERE"/}"
	fi
}

rm -f "$DRIFT_MARKER"
echo "$TABLE" | while IFS=: read -r v appid shim job yap label; do
	[ -n "$v" ] || continue
	subst emit_postinst "$v" "$appid" "$shim" "$job" "$yap" "$label" | put "$HERE/$v/postinst"  0755
	subst emit_prerm    "$v" "$appid" "$shim" "$job" "$yap" "$label" | put "$HERE/$v/prerm"     0755
	subst emit_upstart  "$v" "$appid" "$shim" "$job" "$yap" "$label" | put "$HERE/event.d/$job" 0644
done

if [ "$MODE" = check ]; then
	if [ -e "$DRIFT_MARKER" ]; then
		rm -f "$DRIFT_MARKER"
		echo "FAIL: generated packaging artifacts differ from the template." >&2
		exit 1
	fi
	echo "OK: all generated packaging artifacts match the template."
fi
exit 0
