#!/bin/sh
# Copyright 2026 NotAlexNoyle. Apache-2.0.
#
# Generate the per-variant install artifacts for the three INDEPENDENT Jihad Browser packages
# (cavekit-device-build.md R7 + R8; identity table: context/plans/plan-variant-identity.md):
#
#     packaging/<variant>/postinst      packaging/<variant>/prerm      packaging/event.d/<job>
#     build/webos-oe/recipes-jihad/jihad-ui/jihad-app-scripts.inc     (the OE/bitbake mirror)
#
# WHY A GENERATOR AND NOT THREE HAND-WRITTEN COPIES
#   The three packages share no file on the device — that is the whole point of R7 — but their
#   install LOGIC is identical; only the identity row differs. Hand-maintaining three copies is
#   how the pre-2026-07-31 packaging grew its cross-variant bugs (a `rm -f /tmp/yapserver.
#   jihad-browser*` glob in one script silently owning the other two variants' sockets). One
#   template + one table makes a cross-variant reference impossible to write by accident: every
#   variant-specific string in the output came from this file's TABLE.
#   The generated files are CHECKED IN — they are what actually ships, so they must be readable
#   and diffable — and `--check` proves they still match the template.
#
# WHY THE OE RECIPE IS GENERATED FROM THE SAME TEMPLATE (review F-4)
#   There are two shipping paths — the direct `build-variant-ipk.sh` repack and the OE/bitbake
#   product recipe — and each carried its OWN hand-written copy of postinst/prerm. They drifted:
#   the direct `prerm` was rewritten to do its whole-argument process match in the SHELL after
#   BusyBox 1.17.3's grep (no `-x`) was measured printing its usage text and returning non-zero
#   for every process, silently disabling the fallback kill; the OE mirror kept `grep -qxF` and
#   so shipped the bug the other path had already fixed. Two mirrors of one contract cannot be
#   kept in step by discipline, so the OE bodies are now EMITTED FROM THESE SAME TEMPLATES with
#   the identity row substituted as bitbake `${...}` references instead of literals. There is
#   exactly one implementation of "what install/removal does", and `--check` covers it too.
#
# Usage:
#   sh packaging/gen-variant-scripts.sh            regenerate the 10 artifacts in place
#   sh packaging/gen-variant-scripts.sh --check    fail (exit 1) if any checked-in file has drifted
set -eu

HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)          # repo root — the OE mirror lives outside packaging/

MODE=write
if [ "${1:-}" = "--check" ]; then MODE=check; fi

# ---------------------------------------------------------------------------------------------
# THE IDENTITY TABLE — the only place a variant-specific string may be written.
# Mirrors context/plans/plan-variant-identity.md and build/webos-oe/recipes-jihad/
# jihad-variants.inc (the OE side). Fields, colon-separated:
#
#   1 variant token   2 app id   3 NPAPI shim .so   4 upstart job   5 YAP service name   6 label
#
# Derived, never written by hand: the socket is /tmp/yapserver.<YAP name>, the adapter impl is
# /usr/lib/jihad/<variant>/BrowserAdapterImpl.so, the state dir is /var/palm/jihad/<variant>/.
#
# THE SUFFIXED APP IDS USE A HYPHEN, NEVER A DOT. ipkg keeps package metadata as
# info/<pkgid>.{control,list,prerm} and removes a package by globbing <pkgid>.* — which also
# matches <pkgid>.child.control. A dotted `…jihad-browser.mochi` is a dot-CHILD of the Enyo id, so
# removing the Enyo package deleted Mochi's and Mojo's control scripts and file lists outright,
# leaving them un-uninstallable and their rootfs footprint permanent (P1 against R7/R8; proven
# on-device 2026-08-01 with a dot pair vs. a hyphen pair — see
# ../context/impl/impl-ipkg-prefix-collision.md). A hyphen makes them siblings, not children.
# ---------------------------------------------------------------------------------------------
TABLE="
enyo:net.riverstonerelay.jihad-browser:BrowserAdapterJihad.so:jihad:jihad-browser:Enyo 1.0
mochi:net.riverstonerelay.jihad-browser-mochi:BrowserAdapterJihadMochi.so:jihad-mochi:jihad-browser-mochi:Enyo 2 + Mochi
mojo:net.riverstonerelay.jihad-browser-mojo:BrowserAdapterJihadMojo.so:jihad-mojo:jihad-browser-mojo:Mojo
"

# ---------------------------------------------------------------------------------------------
# TEMPLATES. Written with quoted heredocs so NOTHING expands here: every `$` below belongs to
# the generated script. The generator only substitutes the @@…@@ markers from the table.
# ---------------------------------------------------------------------------------------------

emit_postinst() {
	cat <<'TEMPLATE_POSTINST'
#!/bin/sh
# GENERATED by packaging/gen-variant-scripts.sh — DO NOT EDIT THIS FILE.
#   regenerate: sh packaging/gen-variant-scripts.sh          check: … --check
#
# Jihad Browser — @@LABEL@@ variant (@@APPID@@) — post-install.
# Runs as ROOT under Preware / WebOS Quick Install (palm-install does not run control scripts).
#
# The run-in-place-from-cryptofs install model below — leaving the engine in the app's own
# deviceroot instead of copying it to /media/internal, and doing every rootfs write in a single
# remount-rw window — is adapted from the Atlas browser's
# atlas-browser-app/packaging/ipk-postinst.sh (Apache-2.0, Herman van Hazendonk / Herrie82).
#
# ── INSTALL FOOTPRINT (cavekit-device-build.md R8; enumerated in packaging/README.md) ─────────
# Everything this script creates outside the app's own directory, and nothing else:
#   /usr/lib/BrowserPlugins/@@SHIM@@
#         the NPAPI shim. Unavoidable rootfs write: webOS WebKit builds its plugin/MIME database
#         by scanning /usr/lib/BrowserPlugins at BOOT, and that is the only path it loads a
#         plugin from (Atlas hit the same wall and found no way around it). Bounded + reversed
#         instead of pretended away.
#   /usr/lib/jihad/  and  /usr/lib/jihad/@@V@@/
#         root-owned 0755 directories holding the adapter impl. Mode-pinned EXPLICITLY (F-8):
#         `mkdir -p` applies the INHERITED umask, and the installer has been observed running
#         with `umask 0`, which would leave both 0777 — enough for any local uid to unlink the
#         impl or hardlink-swap it, and the shim validates the impl FILE, never the directory it
#         was loaded out of.
#   /usr/lib/jihad/@@V@@/BrowserAdapterImpl.so
#         the adapter implementation. It lives on the ROOTFS, not in the app bundle, because the
#         shim dlopens it into privileged LunaSysMgr and fails closed unless the file is
#         root-owned and not group/world-writable (review F-161/F-180) — and cryptofs reports
#         EVERY file as 777, so an app-bundle impl could never pass that check.
#   /etc/event.d/@@JOB@@
#         this variant's own upstart job, root-owned 0644. The stock `browserserver` job is
#         never touched. 0644 and not 0755 deliberately: upstart READS a job file, it never
#         execs it, so the execute bit buys nothing and costs a root-run-file's worth of risk.
#   /var/palm/jihad/  and  /var/palm/jihad/@@V@@/
#         root-owned 0755 runtime state: the daemon log and the debug channels, and NOTHING
#         else. Kilobytes of operational state for a root daemon, correctly on ext3. The engine
#         profile and cache deliberately do NOT live here — /var has 49.6 MB free and is shared
#         with system state (see $APP/profile and $APP/cache below). Root-owned and NOT
#         world-writable: it is read by root-privileged code, and /media/internal
#         (world-writable vfat) is exactly the location the shim's trust check exists to
#         distrust.
#
# EVERY ONE OF THOSE IS `chown 0:0`'d (F-7). They are copied out of the app bundle with `cp -a`,
# and `-a` PRESERVES the source's ownership — from /media/cryptofs, an untrusted 0777 filesystem
# whose reported uid is not ours to trust. The impl was already chown'd because the shim refuses
# to dlopen anything else; the shim itself needs it just as much (LunaSysMgr dlopens the shim as
# root and performs NO trust check of its own) and so does the upstart job (init execs it as
# root).
#
# Created at RUNTIME by the daemon, inside the app's own directory, and listed here because
# this variant's prerm removes it (ipkg only tracks files IT installed, so an untracked tree
# would survive removal as residue and break R8's exact-reversal criterion):
#   $APP/profile/   the engine's DURABLE profile (Gecko's ProfD): cookies.sqlite, prefs.js,
#                   permissions, cert overrides.
#   $APP/cache/     the engine's DISPOSABLE local profile (Gecko's ProfLD): cache2 +
#                   startupCache, capped at 50 MB by browser.cache.disk.capacity.
#         Both on cryptofs, not in /var/palm/jihad/@@V@@/: measured 2026-08-01, /var has 49.6 MB
#         free and is shared with system state, while cryptofs has 10.2 GB. This is also where
#         BOTH prior implementations of this browser on this device put them — isis
#         (CookieJarPath/CachePath under /media/cryptofs/.browser) and Atlas (netdata/netcache/
#         cookies.db in its app deviceroot), the latter because /media/internal is VFAT and
#         gives SQLite no real file locking.
#
# NOT written, deliberately:
#   * NOTHING under /media/internal. That vfat volume is the user's USB mass-storage partition
#     and must stay free of app internals (user decision 2026-07-31; Atlas's model). The daemon,
#     libxul, the bundled glibc-2.23 and the GRE resources RUN IN PLACE from $APP/deviceroot/hl
#     on cryptofs — measured live 2026-07-31: /media/cryptofs is fuse.cryptofs (rw,nosuid,nodev)
#     and is NOT noexec, and a binary copied into an app dir was proven to execute there.
#   * No stock file is modified, replaced, moved, or backed-up-and-swapped. In particular
#     /usr/lib/BrowserPlugins/BrowserAdapter.so, …/BrowserAdapterMojo.so and
#     /etc/event.d/browserserver keep their stock bytes.
#   * No file owned by another Jihad variant. Every path above carries this variant's token, so
#     installing this package cannot overwrite, downgrade, or invalidate anything the Enyo /
#     Mochi / Mojo siblings own (R7).
#
# Reversed EXACTLY by this variant's prerm.
set -e                              # review #6: a failed deploy must NOT report success

V=@@V@@
APP=/media/cryptofs/apps/usr/palm/applications/@@APPID@@
DR=$APP/deviceroot
HL=$DR/hl
SHIM=/usr/lib/BrowserPlugins/@@SHIM@@
IMPLDIR=/usr/lib/jihad/@@V@@
IMPL=$IMPLDIR/BrowserAdapterImpl.so
JOB=/etc/event.d/@@JOB@@
STATE=/var/palm/jihad/@@V@@
log() { echo "jihad-postinst($V): $*"; }

# ── 0. preflight ─────────────────────────────────────────────────────────────────────────────
# Nothing on the system is touched until the whole payload is present, so a truncated download
# or a mis-assembled .ipk fails BEFORE it can half-install (review #6).
[ -f "$HL/jihad-browserserver" ] && [ -f "$HL/ld-2.23.so" ] \
  && [ -f "$DR/BrowserPlugins/@@SHIM@@" ] && [ -f "$DR/event.d/@@JOB@@" ] \
  && [ -f "$APP/BrowserAdapterImpl.so" ] || {
	echo "jihad-postinst($V): bundle payload missing under $APP — aborting" >&2; exit 1; }

# ── 1. engine + daemon: RUN IN PLACE, copy nothing ───────────────────────────────────────────
# The whole runtime already sits in the app's own deviceroot on cryptofs and stays there. All
# this step does is make the two things the upstart job execs executable. Non-fatal: cryptofs
# reports every file 777 regardless, and step 3 verifies the result for real.
log "preparing the Goanna daemon (in place, on cryptofs — nothing is copied)..."
chmod 755 "$HL/jihad-browserserver" "$HL/ld-2.23.so" 2>/dev/null || true

# ── 2. the rootfs writes: ONE rw window ──────────────────────────────────────────────────────
# `/` is treated as read-only; the window is opened here and closed by the trap on EVERY exit
# path INCLUDING failure (R8), so a crash mid-install can never leave the rootfs writable.
# /var/palm is created in the same window because it may sit on the read-only rootfs.
log "installing shim + impl + upstart job + state dir (rootfs rw)..."
trap 'mount -o remount,ro / 2>/dev/null || true' EXIT
mount -o remount,rw /
mkdir -p /usr/lib/BrowserPlugins "$IMPLDIR" "$STATE"
# F-8: `mkdir -p` uses the INHERITED umask. The state dir was already mode-pinned; the impl
# directories were not, so under `umask 0` they landed 0777 and any local uid could unlink or
# hardlink-swap the impl the shim is about to dlopen into LunaSysMgr. Pin all four, root-owned
# 0755, NOT world-writable — see the footprint note above.
chown 0:0 /usr/lib/jihad "$IMPLDIR" /var/palm/jihad "$STATE" 2>/dev/null || true
chmod 0755 /usr/lib/jihad "$IMPLDIR" /var/palm/jihad "$STATE"
cp -a "$DR/BrowserPlugins/@@SHIM@@" "$SHIM"
# F-7: `cp -a` preserves the SOURCE's ownership, and the source is the app bundle on cryptofs —
# an untrusted 0777 filesystem. LunaSysMgr dlopens this shim as root with no trust check of its
# own, so it must be root-owned exactly like the impl it loads.
chown 0:0 "$SHIM" 2>/dev/null || true
chmod 0755 "$SHIM"
cp -a "$APP/BrowserAdapterImpl.so" "$IMPL"
# The shim REJECTS an impl that is not root-owned or is group/world-writable, and `cp -a`
# preserves the source's cryptofs-reported 777 — so set both explicitly, or the adapter will
# refuse to load its own implementation.
chown 0:0 "$IMPL" 2>/dev/null || true
chmod 0644 "$IMPL"
# ── this variant's OWN Luna service name (cavekit-ipc-contract.md R4) ────────────────────────
# The app clears cache/cookies over the Luna bus. Upstream calls `palm://com.palm.browserServer/`,
# which is the STOCK daemon — on a device with Jihad installed that call succeeds and clears the
# WRONG browser (measured 2026-08-04). Each variant therefore owns its own service name, the same
# coexistence move already made for the NPAPI MIME, the YAP name, the upstart job and the state
# dir. Registering a name needs the hub's permission, which is what these four files grant.
#
# `exeName` is the path the hub resolves for our process, and that is the BUNDLED LOADER, not the
# daemon binary: the job execs `./ld-2.23.so … ./jihad-browserserver`, so /proc/<pid>/exe is
# ld-2.23.so. Naming jihad-browserserver here would look right and fail.
LSNAME=net.riverstonerelay.@@YAP@@
LSEXE=$DR/hl/ld-2.23.so
mkdir -p /usr/share/ls2/roles/prv /usr/share/ls2/roles/pub \
         /usr/share/dbus-1/system-services /usr/share/dbus-1/services
# COMPACT, single-line JSON — deliberately, for two reasons. This generator rejects a bare `}`
# at column 0 (it would close an OE function body early), and the obvious workaround, indenting
# the JSON, puts a leading SPACE before the opening brace of a file that ls-hubd parses with its
# own C parser. ls-hubd is load-bearing for boot: if it rejects a role file it can take the whole
# UI down with it. One line has no column-0 brace and no leading whitespace, so neither parser
# has anything to object to.
printf '%s' "{\"role\":{\"exeName\":\"$LSEXE\",\"type\":\"regular\",\"allowedNames\":[\"$LSNAME\",\"\"]},\"permissions\":[{\"service\":\"$LSNAME\",\"inbound\":[\"*\"],\"outbound\":[\"*\"]}]}" \
  > /usr/share/ls2/roles/prv/$LSNAME.json
 {
     "role": {
         "exeName":"$LSEXE",
         "type": "regular",
         "allowedNames": ["$LSNAME",""]
     },
     "permissions": [
         {
             "service":"$LSNAME",
             "inbound":["*"],
             "outbound":["*"]
         }
     ]
 }
LSROLE
cp -a /usr/share/ls2/roles/prv/$LSNAME.json /usr/share/ls2/roles/pub/$LSNAME.json
# Type=static: upstart already runs the daemon, so the bus must never try to spawn it.
cat > /usr/share/dbus-1/system-services/$LSNAME.service <<LSSVC
[D-BUS Service]
Name=$LSNAME
Exec=$LSEXE
Type=static
LSSVC
cp -a /usr/share/dbus-1/system-services/$LSNAME.service /usr/share/dbus-1/services/$LSNAME.service
chown 0:0 /usr/share/ls2/roles/prv/$LSNAME.json /usr/share/ls2/roles/pub/$LSNAME.json \
          /usr/share/dbus-1/system-services/$LSNAME.service \
          /usr/share/dbus-1/services/$LSNAME.service 2>/dev/null || true
chmod 0644 /usr/share/ls2/roles/prv/$LSNAME.json /usr/share/ls2/roles/pub/$LSNAME.json \
           /usr/share/dbus-1/system-services/$LSNAME.service \
           /usr/share/dbus-1/services/$LSNAME.service
# ls-hubd reads roles at startup, so the service becomes reachable after the reboot this
# postinst already asks for — not the moment these files land.

cp -a "$DR/event.d/@@JOB@@" "$JOB"
# F-7 again: init execs this job as root, so it is not the app bundle's file to own. 0644, not
# 0755 — upstart READS a job file, it never execs it, so the execute bit is pure surface.
chown 0:0 "$JOB" 2>/dev/null || true
chmod 0644 "$JOB"
sync
# F-9: never swallow a failed restore-to-read-only. R8 requires `/` back to ro on every exit
# path, so if it did not happen, say so — out loud, on stderr, where ipkg records it. The EXIT
# trap stays armed as a second attempt when this one fails.
if mount -o remount,ro /; then
	trap - EXIT
else
	echo "jihad-postinst($V): WARNING: could not restore / to read-only" >&2
fi

# ── 3. verify the deploy actually landed ─────────────────────────────────────────────────────
# BusyBox `cp` can fail with EBADF across these mounts, so believe the filesystem, not $?.
[ -f "$SHIM" ] && [ -f "$IMPL" ] && [ -f "$JOB" ] && [ -d "$STATE" ] \
  && [ -x "$HL/jihad-browserserver" ] && [ -x "$HL/ld-2.23.so" ] || {
	echo "jihad-postinst($V): deploy verification failed" >&2; exit 1; }

# ── 4. runtime kicks — optional, never fatal (a reboot picks all of this up anyway) ───────────
# `stop` first: on an UPGRADE the previous daemon is still bound to /tmp/yapserver.@@YAP@@ and
# still holds the replaced files open, so a bare `start` would fail and leave the old build
# running. Only this variant's job name is used — never a glob, never another variant's job.
set +e
log "restarting the @@LABEL@@ daemon..."
stop @@JOB@@ 2>/dev/null
# `stop` returns before upstart has finished tearing the job down, and a `start` issued into that
# window is dropped ("Job not changed") — leaving the job STOPPED with no error anywhere. Measured
# 2026-08-01: after a three-variant matrix install, jihad-mochi and jihad-mojo were both
# stop/waiting while enyo happened to win the race; started by hand each came up fine
# ("engine up; serving YAP 'jihad-browser-mochi'"). So: wait for the teardown, then start, then
# CONFIRM — and retry, because a deferred/duplicated install can leave upstart in an odd state.
# NB the status format: this device's upstart prints "(NNN/NNN) <job> (start) running,
# process N" / "(stop) waiting" — NOT the modern "start/running". Match BOTH forms, or the
# teardown wait always times out and the confirm below reports a false WARNING for a daemon
# that is in fact running (observed on the 2026-08-02 mochi deploy).
i=0
while [ $i -lt 10 ]; do
	case "$(status @@JOB@@ 2>/dev/null)" in *"stop/waiting"*|*"(stop) waiting"*) break ;; esac
	i=$((i + 1)); sleep 1
done
i=0
while [ $i -lt 3 ]; do
	start @@JOB@@ 2>/dev/null
	sleep 2
	case "$(status @@JOB@@ 2>/dev/null)" in
		*"start/running"*|*"(start) running"*) break ;;
	esac
	i=$((i + 1))
done
case "$(status @@JOB@@ 2>/dev/null)" in
	*"start/running"*|*"(start) running"*) log "daemon job @@JOB@@ is running" ;;
	*) log "WARNING: @@JOB@@ did not start; it will come up on the next boot" ;;
esac
# F-12: there is deliberately NO `killall LunaSysMgr` here. It tears down every card of every
# app — including the OTHER Jihad variants' cards, which is precisely the cross-variant
# interference R7 exists to forbid, arriving from the packaging side. And it never bought the
# thing it was there for: a NEW plugin enters WebKit's MIME database only on a full BOOT,
# because WebKit scans /usr/lib/BrowserPlugins exactly once, at startup. The old comment
# conceded that. Nothing short of a reboot works, so ASK for the reboot instead of taking the
# user's running cards away in exchange for nothing.
log "install complete."
log "REBOOT the device before launching @@LABEL@@ for the first time: webOS WebKit builds its"
log "NPAPI MIME database at boot, so @@SHIM@@ stays unregistered until the next one."
exit 0
TEMPLATE_POSTINST
}

emit_prerm() {
	cat <<'TEMPLATE_PRERM'
#!/bin/sh
# GENERATED by packaging/gen-variant-scripts.sh — DO NOT EDIT THIS FILE.
#   regenerate: sh packaging/gen-variant-scripts.sh          check: … --check
#
# Jihad Browser — @@LABEL@@ variant (@@APPID@@) — pre-removal. Runs as ROOT.
#
# ON A REAL REMOVAL it removes EXACTLY what this variant's postinst created, and nothing else:
#   /usr/lib/BrowserPlugins/@@SHIM@@
#   /usr/lib/jihad/@@V@@/BrowserAdapterImpl.so   (+ the now-empty /usr/lib/jihad/@@V@@)
#   /etc/event.d/@@JOB@@
#   /var/palm/jihad/@@V@@/                       (the runtime state dir, log included)
#   $APP/profile/                                (the engine's DURABLE profile: cookies.sqlite,
#                                                 prefs.js, permissions — see below)
#   $APP/cache/                                  (the engine's DISPOSABLE local profile: cache2
#                                                 + startupCache — see below)
#   /tmp/yapserver.@@YAP@@                       (this variant's socket)
# `/usr/lib/jihad` and `/var/palm/jihad` are only ever `rmdir`'d — that succeeds solely when the
# LAST variant is gone, and can never take a sibling's subdirectory with it.
#
# ON AN UPGRADE it removes NOTHING. See step 0.
#
# ── TWO PROPERTIES THIS SCRIPT EXISTS TO GUARANTEE ───────────────────────────────────────────
# NO REFCOUNT. The 2026-07-29 review (#4) added a loop that counted sibling
# net.riverstonerelay.jihad-browser* app dirs and skipped teardown while any survived, because
# all variants shared one runtime. Under R7 nothing is co-owned, so that loop is DELETED: this
# package unconditionally removes its own files, and no sibling can be affected either way.
#
# NO GLOBS ACROSS VARIANTS. `rm -f /tmp/yapserver.jihad-browser*` (the old code) deletes the
# Mochi and Mojo sockets; `killall jihad-browserserver` kills their daemons (all three variants
# ship a binary with that name). Every operation below names one exact path or matches one
# exact process.
#
# The engine, daemon, bundled glibc and GRE resources live in $APP/deviceroot and go away with
# the app directory, which the installer removes. There is nothing to clean under
# /media/internal because this package never wrote anything there. That teardown shape is
# adapted from the Atlas browser's atlas-browser-app/packaging/ipk-prerm.sh (Apache-2.0,
# Herman van Hazendonk / Herrie82).

V=@@V@@
APP=/media/cryptofs/apps/usr/palm/applications/@@APPID@@
HL=$APP/deviceroot/hl
SHIM=/usr/lib/BrowserPlugins/@@SHIM@@
IMPLDIR=/usr/lib/jihad/@@V@@
IMPL=$IMPLDIR/BrowserAdapterImpl.so
JOB=/etc/event.d/@@JOB@@
SOCK=/tmp/yapserver.@@YAP@@
STATE=/var/palm/jihad/@@V@@
# The engine's profile, BOTH halves, in the app's own directory on cryptofs:
#   $APP/profile   Gecko's ProfD  — durable: cookies.sqlite, prefs.js, permissions
#   $APP/cache     Gecko's ProfLD — disposable: cache2, startupCache
# Not in $STATE: /var has 49.6 MB free and is shared with system state, and both isis
# (CookieJarPath/CachePath under /media/cryptofs/.browser) and Atlas (netdata/netcache/cookies.db
# in its app deviceroot) put these on cryptofs on this exact device — Atlas because /media/internal
# is VFAT, with no hard links and no real file locking, which breaks the network cache AND
# SQLite. See RuntimeProfileDir()/RuntimeCacheDir() in render/goanna/JihadRuntimePaths.h.
#
# The DAEMON creates both at runtime, so ipkg never tracked them and would leave the whole app
# directory behind as residue — exactly the "no residue" half of R8 that a full install->remove
# filesystem diff checks. They are therefore removed HERE, explicitly, on a real removal only:
# an upgrade must not throw away the user's cookies (F-6).
PROFILE=$APP/profile
CACHE=$APP/cache
log() { echo "jihad-prerm($V): $*"; }

# ── 0. is this a REMOVAL or an UPGRADE? ──────────────────────────────────────────────────────
# F-6: this script used to ignore its argument, so an UPGRADE ran the same `rm -rf
# /var/palm/jihad/@@V@@` as a removal — destroying the user's engine profile (cookies, logins,
# site permissions), the daemon log and anything else the state dir holds on EVERY version
# bump. And because ipkg defers control scripts, the new postinst that was supposed to put it
# all back may not run until much later, or at all: the data is gone first and unconditionally.
# ipkg/dpkg call prerm as one of:
#     prerm remove                     a real removal (also `remove in-favour <pkg>`)
#     prerm upgrade <new-version>      this package is being REPLACED, not removed
#     prerm failed-upgrade <old-ver>   an upgrade is being rolled back — still not a removal
#     prerm deconfigure in-favour …    a dependency shuffle — still not a removal
# Only the first purges. Everything else means THIS PACKAGE IS STAYING, so both the state dir
# and the rootfs files (which the new postinst rewrites in place anyway) are left alone — and
# leaving them means a deferred/failed new postinst degrades to "still running the old shim"
# rather than "nothing installed at all".
# No argument at all is treated as `remove`: callers that pass none are doing a plain uninstall,
# and an uninstall that leaves residue fails R8.
ACTION=$1
[ -n "$ACTION" ] || ACTION=remove
case "$ACTION" in
	remove|purge) PURGE=1 ;;
	*)            PURGE=0 ;;
esac

# ── 1. stop THIS variant's daemon ─────────────────────────────────────────────────────────────
# Unconditional, upgrade included: the running daemon owns the socket and holds the replaced
# files open, so the new install cannot come up cleanly until it is gone.
log "stopping the @@LABEL@@ daemon..."
stop @@JOB@@ 2>/dev/null || true
# Fallback for a daemon upstart is not supervising (started by hand, or orphaned by a crash).
# It must not be `killall jihad-browserserver` — that is every variant's daemon. Instead match
# on argv: the upstart job execs `ld-2.23.so --library-path $HL ./jihad-browserserver $HL`, so
# only THIS variant's processes carry THIS app's bundle directory as an exact argument.
#
# The comparison is done in the shell, NOT with `grep -x`: this device ships BusyBox 1.17.3,
# whose grep supports only -HhnlLoqvsriwFE — there is no -x. `grep -qxF` therefore does not
# match-and-fail, it prints its usage text and returns non-zero for EVERY process, silently
# disabling this whole fallback. (Measured on-device 2026-07-31, after the real removal run
# dumped BusyBox's grep usage into the ipkg output.) A plain -F substring match would work
# today but is a trap for later: the Enyo app id is a prefix of the Mochi and Mojo ones, so it
# only stays safe because the path continues "/deviceroot" — one rename away from killing a
# sibling's daemon. An exact whole-argument comparison has no such edge.
for p in /proc/[0-9]*; do
	[ -r "$p/cmdline" ] || continue
	match=0
	while IFS= read -r arg; do
		[ "$arg" = "$HL" ] && { match=1; break; }
	done <<EOF
$(tr '\0' '\n' < "$p/cmdline" 2>/dev/null)
EOF
	[ "$match" = 1 ] && kill "$(basename "$p")" 2>/dev/null || true
done
rm -f "$SOCK"                       # exact socket path — never a glob (see header)

if [ "$PURGE" = 0 ]; then
	log "$ACTION — this package is staying; leaving the rootfs footprint and $STATE untouched"
	exit 0
fi

# ── 2. the rootfs + state removals: ONE rw window, closed on every exit path ──────────────────
log "removing this variant's rootfs components (rw)..."
trap 'mount -o remount,ro / 2>/dev/null || true' EXIT
mount -o remount,rw / || log "WARNING: could not remount / read-write — step 3 will catch what that costs"
rm -f "$SHIM"
rm -f "$IMPL"
rmdir "$IMPLDIR" 2>/dev/null || true
rmdir /usr/lib/jihad 2>/dev/null || true    # succeeds only once the LAST variant is gone
rm -f "$JOB"
# This variant's Luna service name (exact paths, one variant's name — no glob could reach a
# sibling's). Leaving these behind would be rootfs residue that R8 forbids, and would leave the
# hub permitting a name nothing serves.
LSNAME=net.riverstonerelay.@@YAP@@
rm -f /usr/share/ls2/roles/prv/$LSNAME.json /usr/share/ls2/roles/pub/$LSNAME.json \
      /usr/share/dbus-1/system-services/$LSNAME.service \
      /usr/share/dbus-1/services/$LSNAME.service
rm -rf "$STATE"                             # this variant's state dir only
rmdir /var/palm/jihad 2>/dev/null || true   # ditto
sync
# The engine profile + cache are on cryptofs, not the rootfs, so they need no rw window — but
# they do need to go, for the reason at $PROFILE above. Exact paths, both inside THIS variant's
# own app directory; no glob could reach a sibling's.
rm -rf "$PROFILE" "$CACHE"
# F-9: a failed restore-to-read-only is REPORTED, never swallowed (R8 requires `/` back to ro on
# every exit path). It does not by itself fail the removal — the removal above already happened,
# and the EXIT trap gets one more attempt — but it does not get to be silent either.
if mount -o remount,ro /; then
	trap - EXIT
else
	echo "jihad-prerm($V): WARNING: could not restore / to read-only" >&2
fi

# ── 3. verify the removal ACTUALLY happened — believe the filesystem, not $? ──────────────────
# F-9: every step above is best-effort by design (a half-installed package must still be
# removable), and the script then reported success unconditionally. So a failed `mount -o
# remount,rw /` turned removal into a silent no-op while the installer recorded a clean
# uninstall — leaving a stale shim to register an NPAPI MIME on every boot and a stale upstart
# job to respawn against an app directory that no longer exists. postinst already refuses to
# report a deploy it cannot see on disk; this is the same rule applied to the reverse operation.
rc=0
for f in "$SHIM" "$IMPL" "$JOB" "$SOCK" "$STATE" "$PROFILE" "$CACHE"; do
	if [ -e "$f" ]; then log "ERROR: $f still present after removal"; rc=1; fi
done
if [ "$rc" != 0 ]; then
	echo "jihad-prerm($V): removal INCOMPLETE — refusing to report success" >&2
	exit 1
fi

# F-12: no `killall LunaSysMgr` here either — see this variant's postinst. It would take down
# every card of every app (R7's isolation, broken from the packaging side) to achieve a plugin
# re-scan that only a boot performs.
log "removal complete."
log "REBOOT to drop @@SHIM@@ from WebKit's NPAPI MIME database; until then it is registered but"
log "its backing file is gone, so a card asking for that MIME simply fails to instantiate."
exit 0
TEMPLATE_PRERM
}

emit_upstart() {
	cat <<'TEMPLATE_UPSTART'
# GENERATED by packaging/gen-variant-scripts.sh — DO NOT EDIT THIS FILE.
#   regenerate: sh packaging/gen-variant-scripts.sh          check: … --check
#
# Jihad BrowserServer (UXP/Goanna daemon) — @@LABEL@@ variant. Installed to /etc/event.d/@@JOB@@.
#
# This is THIS VARIANT'S OWN upstart job. It does not touch the stock `browserserver` job, and
# it does not touch the other Jihad variants' jobs: stock /usr/bin/BrowserServer keeps serving
# /tmp/yapserver.browser for every other app, and each Jihad variant serves exactly one socket
# (/tmp/yapserver.@@YAP@@ here), reached only by the card whose WebView asks for that variant's
# plugin MIME. upstart supervises this (respawn) so the browser survives a daemon crash.
#
# RUNS IN PLACE. The daemon, libxul, the bundled glibc-2.23 loader and the GRE resources are
# executed straight out of the app's own cryptofs deviceroot — nothing was ever copied to
# /media/internal (the user's vfat USB storage). Verified live 2026-07-31: /media/cryptofs is
# fuse.cryptofs (rw,nosuid,nodev), NOT noexec, and a binary in an app dir executes there. Model
# adapted from the Atlas browser (atlas-browser-app/packaging/ipk-postinst.sh, Apache-2.0,
# Herman van Hazendonk / Herrie82), which runs its WPE engine in place the same way.
#
# ── HARD-WON: LD_LIBRARY_PATH IS SET ONLY VIA `env`, ON THE EXEC LINE ────────────────────────
# It must NEVER be exported into this script's shell. The bundled gcc9 glibc-2.23 is not
# compatible with the device's 2.8 userland, so an exported LD_LIBRARY_PATH makes /bin/rm,
# mkdir, touch — every command below — load the wrong libc and segfault before the daemon ever
# execs. Keep it on the `exec env` line and nowhere else.
start on stopped fontconfig_cache
stop on started start_update
# ── AND stop when the system is going down, EARLY ────────────────────────────────────────────
# Without this we are killed by the late generic sweep at reboot, which runs at the same moment
# cryptofs is torn down — and the engine profile lives on cryptofs. Our SIGTERM handler flushes
# the add-on database and prefs, so it was writing and mmap-reading files whose backing store
# was disappearing: two daemons took SIGBUS (signal 7) on 2026-08-05, wrote crash dumps onto a
# /var that was unmounting, and the device would not boot again.
#
# The stock browserserver has only the start_update clause and gets away with it because it does
# no work on SIGTERM — it just dies. We do work, so we have to be asked earlier. Runlevel 0 is
# halt and 6 is reboot; `stop on runlevel [06]` is the platform's own idiom for this (ntpdate-sync
# uses it), and it fires while the filesystems are still mounted, which is the whole point.
# Boot runlevels are 2/3, so this never interferes with starting.
stop on runlevel [06]

description "Jihad BrowserServer (Goanna) — @@LABEL@@"

script
	APP=/media/cryptofs/apps/usr/palm/applications/@@APPID@@
	HL=$APP/deviceroot/hl
	STATE=/var/palm/jihad/@@V@@

	# The state dir is created root-owned 0755 by postinst; recreate it best-effort because a
	# device reset / GC wipes /var. If it is genuinely unavailable (e.g. a read-only rootfs at
	# this point in boot) fall back to /dev/null rather than letting a failed redirect kill the
	# job and spin the respawn limit — the daemon itself is still perfectly able to run.
	mkdir -p "$STATE" 2>/dev/null || true
	LOG=$STATE/daemon.log
	touch "$LOG" 2>/dev/null || LOG=/dev/null
	exec >>"$LOG" 2>&1

	# Only this variant's own socket — an exact path, never `…jihad-browser*`, which would
	# delete the other variants' sockets out from under their running daemons.
	rm -f /tmp/yapserver.@@YAP@@

	cd "$HL" || exit 1
	# NB: do NOT set JIHAD_DUMP in normal operation — it makes every paint write a ~2.2 MB PPM
	# char-by-char (fputc), which added ~400 ms of latency PER KEYSTROKE. Set it only when
	# debugging what the engine renders, and point it INSIDE the state dir, never at
	# /media/internal (env JIHAD_DUMP=$STATE/frame.ppm).
	# JIHAD_BS_NAME is this variant's YAP service name — it is what makes the socket, and
	# therefore the whole daemon<->adapter channel, unique per variant.
	# JIHAD_STATE_DIR tells the daemon where its operational state (the log and the debug
	# channels) belongs; it must never fall back to the user's storage. The engine PROFILE and
	# CACHE are NOT here — they go to $APP/profile and $APP/cache on cryptofs, where isis and
	# Atlas both put them, because /var has 49.6 MB free and is shared with system state (see
	# RuntimeProfileDir()/RuntimeCacheDir() in render/goanna/JihadRuntimePaths.h).
	# ICU_DATA is REQUIRED, not a nicety. libxul loads its Unicode tables from icudt78l.dat at
	# XPCOM startup; the path compiled into the engine is the BUILD machine's, which does not
	# exist here, and ICU has no notion of "next to the library". Without this the daemon aborts
	# on every single start with
	#     ###!!! ABORT: u_init() failed: file .../xpcom/build/XPCOMInit.cpp, line 698
	# and upstart respawns it forever. Diagnosed on-device 2026-07-31: identical invocation, the
	# only difference being ICU_DATA, gets past u_init() and on into fontconfig.
	# HOME IS LOAD-BEARING, not hygiene. UXP reads it via
	# `nsDependentCString(PR_GetEnv("HOME"))` with NO null check (xpcom/io/
	# SpecialSystemDirectory.cpp GetUnixHomeDir, xpcom/io/nsAppFileLocationProvider.cpp),
	# so an unset HOME is strlen(NULL) and an instant SIGSEGV at address 0 during
	# engine startup. An upstart job inherits init's environment, which on webOS 3 has
	# no HOME — which is why this crashed 100% on device and never in the container
	# (podman always passes -e HOME=...). Diagnosed 2026-08-01 from the daemon's own
	# fault report. The daemon also sets this itself if it is missing, so hand-launched
	# runs are covered; it is repeated here because this is where the daemon's
	# environment is actually defined, and a reader must not have to know the C++ to
	# see it. Pointed at the state dir so anything Gecko writes under $HOME stays
	# inside the footprint this variant's prerm removes.
	exec env LD_LIBRARY_PATH="$HL" ICU_DATA="$HL" HOME="$STATE" \
	         JIHAD_BS_NAME=@@YAP@@ JIHAD_OFFSCREEN=1 JIHAD_DISABLE_OMTC=1 \
	         JIHAD_STATE_DIR="$STATE" \
	    ./ld-2.23.so --library-path "$HL" ./jihad-browserserver "$HL"
end script

respawn
respawn limit 10 5
TEMPLATE_UPSTART
}

# ---------------------------------------------------------------------------------------------
# THE OE/BITBAKE MIRROR (review F-4).
#
# Same two bodies, wrapped as `pkg_postinst_${PN}` / `pkg_prerm_${PN}` and substituted with
# bitbake variable references instead of literals, so the OE product recipe and the direct
# `.ipk` repack cannot diverge again. Requirements this imposes on the templates above:
#
#   * they must contain NO `${...}`. bitbake expands `${VAR}` inside a function body at parse
#     time, so a shell `${1:-remove}` in the template would be handed to bitbake's expander (it
#     happens to survive today, being an unknown variable — but that is luck, not a contract).
#     Enforced below, not trusted.
#   * no line may be exactly `}` at column 0 — that is how bitbake's BBHandler.feeder decides a
#     function body has ended. Also enforced below.
#   * `\`-continued lines are fine: bitbake joins them (stripping the leading whitespace of the
#     continuation) before feeding, and every continuation here joins into valid shell. The
#     existing recipe has shipped that shape since 2026-07-31.
# ---------------------------------------------------------------------------------------------
emit_oe() {
	cat <<'TEMPLATE_OE_HEAD'
# GENERATED by packaging/gen-variant-scripts.sh — DO NOT EDIT THIS FILE.
#   regenerate: sh packaging/gen-variant-scripts.sh          check: … --check
#
# The OE/bitbake mirror of packaging/<variant>/{postinst,prerm}, emitted from the SAME templates
# with the identity row substituted as bitbake ${...} references. `require`d by jihad-app.inc.
#
# WHY GENERATED: the two shipping paths each used to carry a hand-written copy of these bodies
# and they drifted — the direct prerm was rewritten to do its whole-argument process match in
# the shell after BusyBox 1.17.3's grep (which has no `-x`) was measured printing its usage text
# and returning non-zero for EVERY process, silently disabling the fallback kill, while this
# mirror kept `grep -qxF` and shipped the bug the other path had already fixed (review F-4).
# One template, two renderings, one `--check`.
#
# `if [ -n "$D" ]; then exit 1; fi` in each body defers to first boot when the package is
# installed into an image: every step below touches the LIVE rootfs and a running upstart,
# neither of which exists at image-assembly time.
TEMPLATE_OE_HEAD
	printf '\n'
	printf 'pkg_postinst_${PN} () {\n'
	printf 'if [ -n "$D" ]; then exit 1; fi\n'
	emit_postinst | sed -e '1{/^#!/d;}'
	printf '}\n\n'
	printf 'pkg_prerm_${PN} () {\n'
	printf 'if [ -n "$D" ]; then exit 1; fi\n'
	emit_prerm | sed -e '1{/^#!/d;}'
	printf '}\n'
}

# The two invariants the OE rendering depends on, checked against the templates themselves so a
# later edit cannot quietly break the recipe. Captured and matched with `case`, never piped into
# `grep -q` — that pattern has failed OPEN on an R8 assertion in this repo twice already.
TEMPLATE_TEXT="$(emit_postinst)
$(emit_prerm)"
case "$TEMPLATE_TEXT" in
	*'${'*)
		echo "FAIL: a template contains \${...}; bitbake would expand it in the OE mirror." >&2
		exit 1 ;;
esac
case "
$TEMPLATE_TEXT
" in
	*"
}
"*)
	echo "FAIL: a template has a bare '}' at column 0; that ends the OE function body early." >&2
	exit 1 ;;
esac

# ---------------------------------------------------------------------------------------------
# Driver.
# ---------------------------------------------------------------------------------------------
subst() {
	# $1 emitter, then the six table fields.
	"$1" | sed \
		-e "s|@@V@@|$2|g" \
		-e "s|@@APPID@@|$3|g" \
		-e "s|@@SHIM@@|$4|g" \
		-e "s|@@JOB@@|$5|g" \
		-e "s|@@YAP@@|$6|g" \
		-e "s|@@LABEL@@|$7|g"
}

# Write $1 (mode $2) with the content on stdin, or — in --check mode — compare and flag drift.
# Both the `while` loop and the right-hand side of the pipe that feeds this run in SUBSHELLS, so
# a shell variable could not carry a drift verdict back out; the marker file can.
DRIFT_MARKER=$HERE/.gen-variant-scripts.drift
put() {
	dest=$1
	mode=$2
	tmp=$dest.gen.$$
	mkdir -p "$(dirname "$dest")"
	cat > "$tmp"
	if [ "$MODE" = check ]; then
		if cmp -s "$tmp" "$dest"; then
			echo "  ok      ${dest#"$ROOT"/}"
		else
			echo "  DRIFTED ${dest#"$ROOT"/}" >&2
			: > "$DRIFT_MARKER"
		fi
		rm -f "$tmp"
	else
		chmod "$mode" "$tmp"
		mv "$tmp" "$dest"
		echo "  wrote   ${dest#"$ROOT"/}"
	fi
}

rm -f "$DRIFT_MARKER"
echo "$TABLE" | while IFS=: read -r v appid shim job yap label; do
	[ -n "$v" ] || continue
	subst emit_postinst "$v" "$appid" "$shim" "$job" "$yap" "$label" | put "$HERE/$v/postinst"  0755
	subst emit_prerm    "$v" "$appid" "$shim" "$job" "$yap" "$label" | put "$HERE/$v/prerm"     0755
	subst emit_upstart  "$v" "$appid" "$shim" "$job" "$yap" "$label" | put "$HERE/event.d/$job" 0644
done

# The OE mirror: ONE rendering for all three variants, because the recipe is itself parametrized
# — the "identity row" handed to `subst` here is the set of bitbake variables jihad-variants.inc
# derives from the recipe's single `JIHAD_VARIANT` fact. There is no @@LABEL@@ column on the OE
# side, so the variant token stands in for it.
subst emit_oe \
	'${JIHAD_VARIANT}' '${WEBOS_APP_ID}' '${JIHAD_SHIM_SO}' \
	'${JIHAD_UPSTART_JOB}' '${JIHAD_YAP_NAME}' '${JIHAD_VARIANT}' \
	| put "$ROOT/build/webos-oe/recipes-jihad/jihad-ui/jihad-app-scripts.inc" 0644

if [ "$MODE" = check ]; then
	if [ -e "$DRIFT_MARKER" ]; then
		rm -f "$DRIFT_MARKER"
		echo "FAIL: generated packaging artifacts differ from the template." >&2
		exit 1
	fi
	echo "OK: all generated packaging artifacts match the template."
fi
exit 0
